In [8]:
import laurent_modulo_p as lmp
import free_scripts as bf
from itertools import product
import numpy as np 
import json
from importlib import reload
reload(bf)
reload(lmp)

<module 'laurent_modulo_p' from '/Users/borisgolikov/Desktop/Burau/ai_in_math/burau_representation/scripts/laurent_modulo_p.py'>

In [2]:
symbol_to_matrix = {
    "A": lmp.A,
    "B": lmp.B,
    "a": lmp.a,
    "b": lmp.b
}
a = bf.calculate_products(symbol_to_matrix,4)


0
0
1
1
2
2
3
3


In [8]:
mod2 = {key: value.convert_to_modulo(2) for key, value in a.items()}

In [9]:
matrices_mod2 = {
    "A": lmp.A.convert_to_modulo(2),
    "B": lmp.B.convert_to_modulo(2),
    "a": lmp.a.convert_to_modulo(2),
    "b": lmp.b.convert_to_modulo(2)
}
b = {key: value for key, value in mod2.items() if len(key) == 9}  
print(len(b))

26244


In [10]:
c = b
print(len(c))
for i in range(50):
    c = bf.cut_by_degree(c,3)
    print(len(c))
    c = bf.extend_in_all_ways(matrices_mod2,c,1)
    print(len(next(iter(c))),bf.min_degree_in_array(c))

26244
16160
10 (4, 0, [])
26832
11 (4, 0, [])
33608
12 (4, 0, [])
35568
13 (4, 0, [])
37344
14 (4, 0, [])
36984


KeyboardInterrupt: 

In [12]:

c = b
for i in range(50):
    c = bf.get_matrices_within_threshold(c,4)
    c = bf.extend_in_all_ways(matrices_mod2,c,3)
    print(len(next(iter(c))),bf.min_degree_in_array(c))



12 (4, 0, [])
15 (5, 0, [])
18 (4, 0, [])
21 (4, 0, [])
24 (4, 0, [])
27 (3, 0, [])
30 (2, 0, [])
33 (1, 0, [])
36 (0, 202, ['abAbbbbbAbbabaaababbAbbbbbAbbbbAbbbA', 'bbabbabbbabbbabbbabbabbbbAAbAbAbAAbb', 'aBABBBABBBBABBaBBaBaBaBBaBBABBBBABBA', 'bAAbAAAAbAAAbAAAbAAAAbAABAABABABAABB', 'aBABBBABBABBABBBABBaBBBaBBaBBaBBBaBA', 'bABAAABAAAABAbbbabbabbbaBaaBaBaBaaBB', 'bbAbbAbbbAbbbAbbbAbbAbbbbaabababaabb', 'BaBBaBaBaBBaBAAABAABAAAbabbbbabbbabb', 'AABBABABABBABaaaBaaBaaabAbbbbAbbbAba', 'bababbabbabbababbbbAbAbbAbbAbbAbAbbb', 'BaBBBaBBaBBBAbAAAAbAAAbAbaabababaabb', 'baabaaaabaaabaaabaaaabaaBaaBaBaBaaBB', 'BBaaBaBaBaaBabbbabbabbbABAAAABAAABAb', 'BabaaabaabaabaaabaaBaaaBaaBaaBaaaBab', 'aBABBBBABBBABBBABBBBABBaBBaBaBaBBaBA', 'aBaBBaBaBaBBaBBABBBBABBBABBBABBBBABA', 'AbAbbbbAbbbAbbbAbbbbAbbabbabababbaba', 'AABBABABABBABBaBBBBaBBBaBBBaBBBBaBBa', 'AbabbabababbabbAbbbbAbbbAbbbAbbbbAba', 'bbAbAbbAbbAbbAbAbbbbababbabbabbababb', 'AAABBABABABBAAAAbAAbAAAbAAAbAAAbAAbA', 'AAAbAbAAbAAbAAbAbAAAABABAABAABAABA

KeyboardInterrupt: 

In [3]:
mod3 = {key: value.convert_to_modulo(3) for key, value in a.items()}
print(bf.get_degree_picture(mod3,9))
matrices_mod3 = {
    "A": lmp.A.convert_to_modulo(3),
    "B": lmp.B.convert_to_modulo(3),
    "a": lmp.a.convert_to_modulo(3),
    "b": lmp.b.convert_to_modulo(3)
}
b = {key: value for key, value in mod3.items() if len(key) == 5}  
print(len(b))

{0: 0, 1: 4, 2: 20, 3: 108, 4: 228, 5: 124, 6: 0, 7: 0, 8: 0, 9: 0}
None
324


In [7]:
c = b
for i in range(1000):
    c = bf.tiered_sampling(c,[1],0)
    print(len(c))
    c = bf.extend_in_all_ways(matrices_mod3,c,1)
    print(len(next(iter(c))),bf.min_degree_in_array(c))

['AABAA', 'AAbAA', 'ABAAB', 'ABABA', 'ABBAB', 'AbAAb', 'AbAbA', 'AbbAb', 'BAABA', 'BABAB', 'BABBA', 'BBABB', 'BBaBB', 'BaBBa', 'BaBaB', 'BaaBa', 'aBBaB', 'aBaBa', 'aBaaB', 'aaBaa', 'aabaa', 'abaab', 'ababa', 'abbab', 'bAAbA', 'bAbAb', 'bAbbA', 'baaba', 'babab', 'babba', 'bbAbb', 'bbabb', 'AAABA', 'AAAbA', 'AABAB', 'AABAb', 'AABBA', 'AABaB', 'AAbAB', 'AAbAb', 'AAbab', 'AAbbA', 'ABAAA', 'ABAAb', 'ABABB', 'ABABa', 'ABAbA', 'ABAba', 'ABAbb', 'ABBAA', 'ABBAb', 'ABBBA', 'ABBaB', 'ABaBA', 'ABaBB', 'ABaBa', 'ABaaB', 'ABaba', 'AbAAA', 'AbAAB', 'AbABA', 'AbABB', 'AbABa', 'AbAba', 'AbAbb', 'AbaBa', 'Abaab', 'AbabA', 'Ababa', 'Ababb', 'AbbAA', 'AbbAB', 'Abbab', 'AbbbA', 'BAAAB', 'BAABB', 'BAABa', 'BAAbA', 'BABAA', 'BABAb', 'BABBB', 'BABBa', 'BABaB', 'BABaa', 'BABab', 'BAbAA', 'BAbAB', 'BAbAb', 'BAbab', 'BAbbA', 'BBAAB', 'BBABA', 'BBABa', 'BBAbA', 'BBBAB', 'BBBaB', 'BBaBA', 'BBaBa', 'BBaaB', 'BBaba', 'BaBAA', 'BaBAB', 'BaBAb', 'BaBBA', 'BaBBB', 'BaBaa', 'BaBab', 'BaaBA', 'BaaBB', 'BaaaB', 'Baaba', 

ValueError: Matrix dimensions must align for multiplication.

In [5]:
mod5 = {key: value.convert_to_modulo(5) for key, value in a.items()}

In [ ]:
print(bf.get_degree_picture(mod5,9))
d = {key: value for key, value in mod5.items() if len(key) == 9}  
matrices_mowqdnvert_to_modulo(5),
    "B": lmp.B.convert_to_modulo(5),
    "a": lmp.a.convert_to_modulo(5),
    "b": lmp.b.convert_to_modulo(5)
}
c = d
for i in range(10000):
    c = bf.get_matrices_within_threshold(c,3,8000)
    print(len(c))
    c = bf.extend_in_all_ways(matrices_mod5,c,1)
    print(len(next(iter(c))),bf.min_degree_in_array(c))

{0: 0, 1: 4, 2: 20, 3: 124, 4: 764, 5: 3324, 6: 9980, 7: 14044, 8: 9060, 9: 2044}
None
17336
10 (4, 0, [])
23534
11 (4, 0, [])
26793
12 (4, 0, [])
28209
13 (4, 0, [])
28239
14 (4, 0, [])
28678
15 (5, 0, [])
28284
16 (5, 0, [])
28175
17 (4, 0, [])
28249
18 (5, 0, [])
28348
19 (5, 0, [])
28379
20 (5, 0, [])
28087
21 (5, 0, [])
28641
22 (5, 0, [])
28750
23 (5, 0, [])
28588
24 (5, 0, [])
28202
25 (5, 0, [])
28411
26 (5, 0, [])
28424
27 (5, 0, [])
27923
28 (5, 0, [])
28137
29 (5, 0, [])
27906
30 (5, 0, [])
28163
31 (5, 0, [])
27933
32 (6, 0, [])
28162
33 (6, 0, [])
27992
34 (5, 0, [])
28300
35 (6, 0, [])
28332
36 (6, 0, [])
28445
37 (6, 0, [])
28679
38 (6, 0, [])
28774
39 (6, 0, [])
28820
40 (6, 0, [])
28588
41 (5, 0, [])
28439
42 (6, 0, [])
28539
43 (6, 0, [])
28503
44 (6, 0, [])
28390
45 (6, 0, [])
28321
46 (6, 0, [])
28224
47 (6, 0, [])
28240
48 (6, 0, [])
28267
49 (6, 0, [])
28363
50 (6, 0, [])
29019
51 (6, 0, [])
28728
52 (6, 0, [])
29162
53 (6, 0, [])
29042
54 (6, 0, [])
29231
55 (6, 

KeyboardInterrupt: 

In [10]:
import math
matrices = {
    "A": lmp.A(math.sqrt(2)),
    "B": lmp.B(math.sqrt(2)),
    "a": lmp.a(math.sqrt(2)),
    "b": lmp.b(math.sqrt(2))
}
print(bf.word_to_matrix(matrices,"aBaBaaBaaBaBaaBaBaaBaBaaBaaBaBaaBaBaaBaaBaBaaBaBaaBaBaaBaaBaBaaBaBaaBaBaaBaaBaBaaBaBaaBaBaaBaaBaBaaBaBaaBaaBaBaaBaBaaBaBaaBaaBaBaBABBABBABABBABABBABBABABBABBABABBABBABABBABABBABBABABBABBABABBABABBABBABABBABBABABBABBABABBABABBABBABABBABBABABBABBABABBABABBABBABABBABBABABBABBABABBABABBABBABABBABBABABBABABBABBABABBABBABABBABBABABBABABBABBAB"))
print(bf.word_to_matrix(matrices_mod3,"bababbabbababbababbababbabbababbababbabbababbababbababbabbababbababbababbabbababbababbababbabbababbababbabbababbababbababbabbababaBaaBaaBaBaaBaBaaBaaBaBaaBaaBaBaaBaaBaBaaBaBaaBaaBaBaaBaaBaBaaBaBaaBaaBaBaaBaaBaBaaBaaBaBaaBaBaaBaaBaBaaBaaBaBaaBaaBaBaaBaBaaBaaBaBaaBaaBaBaaBaaBaBaaBaBaaBaaBaBaaBaaBaBaaBaBaaBaaBaBaaBaaBaBaaBaaBaBaaBaBaaBaaBa"))
print(bf.word_to_matrix(matrices_mod3,"ABABAABAABABAABABAABABAABAABABAABABAABAABABAABABAABABAABAABABAABABAABABAABAABABAABABAABABAABAABABAABABAABAABABAABABAABABAABAABABABaBBaBBaBaBBaBaBBaBBaBaBBaBBaBaBBaBBaBaBBaBaBBaBBaBaBBaBBaBaBBaBaBBaBBaBaBBaBBaBaBBaBBaBaBBaBaBBaBBaBaBBaBBaBaBBaBBaBaBBaBaBBaBBaBaBBaBBaBaBBaBBaBaBBaBaBBaBBaBaBBaBBaBaBBaBaBBaBBaBaBBaBBaBaBBaBBaBaBBaBaBBaBBaB"))
print(bf.word_to_matrix(matrices_mod3,"aBaaBaaBaBaaBaBaaBaaBaBaaBaaBaBaaBaaBaBaaBaBaaBaaBaBaaBaaBaBaaBaBaaBaaBaBaaBaaBaBaaBaaBaBaaBaBaaBaaBaBaaBaaBaBaaBaaBaBaaBaBaaBaaBaBaaBaaBaBaaBaaBaBaaBaBaaBaaBaBaaBaaBaBaaBaBaaBaaBaBaaBaaBaBaaBaaBaBaaBaBaaBaaBabababbabbababbababbababbabbababbababbabbababbababbababbabbababbababbababbabbababbababbababbabbababbababbabbababbababbababbabbabab"))
print(bf.word_to_matrix(matrices_mod3,"abaabaababaababaabaababaabaababaabaababaababaabaababaabaababaababaabaababaabaababaabaababaababaabaababaabaababaabaababaababaabaababaabaababaabaababaababaabaababaabaababaababaabaababaabaababaabaababaababaabaabaBaBaBBaBBaBaBBaBaBBaBaBBaBBaBaBBaBaBBaBBaBaBBaBaBBaBaBBaBBaBaBBaBaBBaBaBBaBBaBaBBaBaBBaBaBBaBBaBaBBaBaBBaBBaBaBBaBaBBaBaBBaBBaBaB"))

[[nan nan nan]
 [nan nan nan]
 [nan nan nan]]


ValueError: Matrix dimensions must align for multiplication.

In [12]:
import math
matrices = {
    "A": lmp.A(math.sqrt(2)),
    "B": lmp.B(math.sqrt(2)),
    "a": lmp.a(math.sqrt(2)),
    "b": lmp.b(math.sqrt(2))
}
print(bf.word_to_matrix(matrices,"aBaaBaaBaBaaBaBaaBaABBABBABABBABBABABBABABBABBABABBABBABABBABBABABBABABBABBABABBABBABABBABBABABBABABBABBABABBABBABABBABBABABBABABBABBABABBABBABABBABABBABBABABBABBABABBABBABABBABABBABBAB"))

[[ 1.45275197e+125 -7.99003493e+124  9.06362795e+124]
 [ 6.48796228e+124 -3.56833419e+124  4.04779876e+124]
 [ 2.19521779e+125 -1.20735454e+125  1.36958254e+125]]
